import Head from 'next/head'
import Ola from "../components/ola"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Ola/>
      </main>
    </div>
  )
}
