import Head from 'next/head'
import dynamic from 'next/dynamic'

const DynamicComponentWithNoSSR = dynamic(
  () => import('../components/ola'),
  { ssr: false }
)

export default function Home() {
  return (
    <div>
      <Head>
        <title>Function-SIN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <DynamicComponentWithNoSSR/>
      </main>
    </div>
  )
}
